# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea6e303d624b91e7f6430e921bd51035ca419923fbf28675e2964270bacbbf428c5213fcf1c0ee16d7559ae4445d6d62c22bc8da2d11093b65a1e2a12127414

test:
  secret_key_base: 48da851890668464dfc61b74d176c34b6ec00215a60ebc9d412c23232676544313682fb796ddd1ed58eb503003ba1acd9bfacf11406a8bfc95fdb71573b0aecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
